src/config/routes.rb
Rails.application.routes.draw do
  resources :trips
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get '/success', to: "payments#success", as: "payment_success"
  post '/payments/webhook', to: "payments#webhook", as: "webhook"
  post '/payments', to: "payments#create_payment_intent", as: "create_payment_intent"

end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/cabin.rb
class Cabin < ApplicationRecord
end

src/app/models/order.rb
class Order < ApplicationRecord
    belongs_to :trip
    belongs_to :buyer, foreign_key: 'buyer_id', class_name: "User"
    belongs_to :seller, foreign_key: 'seller_id', class_name: "User"
end

src/app/models/planet.rb
class Planet < ApplicationRecord
end

src/app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

src/app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :planet
  belongs_to :cabin
  accepts_nested_attributes_for :cabin
  has_one_attached :picture
  before_validation :convert_price_to_cents, if: :price_changed?


  private

  def convert_price_to_cents 
    self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
  end 
end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :trips

  has_many :sold_orders, class_name: "Order", foreign_key: "seller_id"
  has_many :bought_orders, class_name: "Order", foreign_key: "buyer_id"        
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation)}

            devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:name, :email, :password, :current_password)}
        end
end

src/app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
    def home
    
    end

end

src/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success
        @order = Order.find_by_trip_id(params[:id])
    end

    def create_payment_intent
        trip = Trip.find(params[:id])
        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'], 
            customer_email: current_user&.email, #current_user && current_user.email 
            line_items: [{
              name: trip.id, 
              description: trip.description, 
              amount: trip.price,
              currency: 'aud', 
              quantity: 1
            }], 
            payment_intent_data: {
              metadata: {
                user_id: current_user&.id,
                trip_id: trip.id
              }
            }, 
            success_url: "#{root_url}/success?id=#{trip.id}", 
            cancel_url: "#{root_url}/trips"
          )
      
          @session_id = session.id 
    end 

    def webhook
        pp "test"
        payment_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)
        pp payment
        trip_id = payment.metadata.trip_id
        buyer_id = payment.metadata.user_id
        trip = Trip.find(trip_id)
        trip.update(sold: true)
        Order.create(trip_id: trip_id, buyer_id: buyer_id, seller_id: trip.user_id, payment_id: payment_id, reciept: payment.charges.data[0].receipt_url)
    end
end

src/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorise_user, only: [:edit, :update, :destroy]
  before_action :set_form_vars, only: [:new, :edit]

  # GET /trips or /trips.json
  def index
    @trips = Trip.all.includes(:planet)
  end

  # GET /trips/1 or /trips/1.json
  def show
   
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  #create a trips
  def create
    p trip_params
    @trip = current_user.trips.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def authorise_user
      if current_user.id != @trip.user_id
        flash[:error] = "You're not allowed to do that"
        redirect_to trips_path
      end 
    end 

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:planet_id, :price, :sold, :cabin_id, :picture, :description)
    end

    def set_trips
      @trip = Trip.find(params[:id])
    end

    def set_form_vars
      @planets = Planet.all
      @cabins = Cabin.all
    end

end

src/app/helpers/application_helper.rb
module ApplicationHelper
    def select_alert_subclass(input)
        case input
        when 'notice'
            return 'info'
        when 'success'
            return 'success'
        when 'error'
            return 'danger'
        when 'alert'
            return 'warning'
        else
            return 'info'
        end 
    end 
end

src/app/helpers/pages_helper.rb
module PagesHelper
end

src/app/helpers/payments_helper.rb
module PaymentsHelper
end

src/app/helpers/trips_helper.rb
module TripsHelper
def image_select(trip)
        return trip.picture if trip.picture.attached?
        #if no picture attached use default image
        return "default_image.jpg"
    end
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceUp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%flash.each do |key,value|%>
      <div class="alert alert-<%=select_alert_subclass(key)%> alert-dismissable fade show" role="alert">
        <%=value%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true"> &times; </span>
        </button>
      </div>
    <%end%>
    
    <%=render '/shared/navbar'%>
    <%= yield %>
  </body>
</html>

src/app/views/pages/home.html.erb
<main class="landing">
  <h1>Welcome to Space Up</h1>

</main>

src/app/views/payments/create_payment_intent.js.erb
const stripe = Stripe("<%=Rails.application.credentials.dig(:stripe, :public_key)%>")

stripe.redirectToCheckout({
    sessionId: "<%=@session_id%>"
});

src/app/views/payments/success.html.erb
<p> Thank you for buying a trip <a href=<%=@order.reciept%>>View Reciept</a></p>

src/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top"> 
    <div class="navbar-">
      <%= image_tag("default_image.jpg", width: '70px' )%>
    </div>

    <div class= "container-fluid"> 
        <%=link_to "Space Up", root_path, class:"nav-link"%>
    </div>

    <ul class="navbar-nav mr-5-lg"> 

    <% if user_signed_in? %>
        <li class="nav-item">
            <%=link_to "Trips", trips_path, class: "nav-link"%>
        </li> 
        
        <li class="nav-item">
            <%=link_to "Create a trip", new_trip_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
            <%=link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
    <%else%>
        <li class="nav-item">
            <%=link_to "Log in", new_user_session_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
            <%=link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
        </li>

    <%end%>

    </ul>
</nav>

src/app/views/trips/_form.html.erb
<%= form_with(model: trip, local:true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group mb-3">
    <%= form.label :planet_id , class:"form-label" %>
    <%= form.select :planet_id, @planets.map {|p| [p.name, p.id]}, class: "form-select" %>
  </div>

  <h5 class="mb-2 ml-2"> Cabins </h5>

  <div class="form-check mb-3">
      <%=form.collection_radio_buttons :cabin_id, @cabins, :id, :name do |b| %>
      <%= b.label class: "form-label" %>
      <%= b.radio_button class: "form-check-line mr-2" %>
    <%end%>
  </div>

<div class="form-group mb-3 ml-2">
    <%= form.label :description , class:"col form-label" %>  
    <%= form.text_area :description %>
</div>  

 <div class="form-group mb-3 ml-2">
    <%= form.label :price , class:"col form-label" %>  
    <%= form.number_field :price, step: "0.01" %>
</div>

<div class="form-group mb-3 ml-2">
    <%= form.label :picture , class:"col form-label" %>  
    <%= form.file_field :picture, class: "form-control-file", accept: "image/jpg,image/png" %>
</div>

  <div class="form-group mb-3">
    <%= form.submit %>
  </div>

  

<% end %>

src/app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

src/app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Planet</th>
      <th>Cabin</th>
      <th>Price</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.user_id %></td>
        <td><%= trip.planet.name %></td>
        <td><%= trip.cabin.name %></td>
        <td><%= trip.price %></td>
        <td><%= trip.sold %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

src/app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

src/app/views/trips/show.html.erb
<div class='container d-flex flex-column flex-md-row px-2 my-2 my-md-5'>
  <div class='content col-12 col-md-7 col-lg-8 p-0 pr-md-3'>
    <div class='col-12 p-0 main-preview mb-4'>
      <%=image_tag image_select(@trip), class: "thumbnail card-img top"%>
    </div>
  </div>
  <div class= 'sidebar col-lg-4 p-0 mx-2 d-md-block'>
    <h1 class='mb-sm-2 mb-md-5'><%=@trip.user.username%></h1>
    <h4 class='text-muted'>Cabin: <%=@trip.cabin.name.capitalize%></h4>
    <br/>
    <p class='blockquote mt-2'><%=@trip.description%></p>
    <%if current_user && @trip.sold == false%>
      <%= button_to "Buy: $#{@trip.price / 100.0}", create_payment_intent_path, method: :post, remote: true, params:{id: @trip.id}, class: "btn btn-primary p-3"%>
    <%elsif @trip.sold == true%>
      <button class='btn btn-secondary' disabled>SOLD</button>
    <%else%>
      <%=button_to "Login to buy", new_user_session_path, class: "btn btn-info"%>
    <%end%>
  </div>
</div>
<div class='container'>
  <div class ='d-flex justify-content-evenly'>
    <%= link_to 'Edit', edit_trip_path(@trip), class: "btn btn-warning mr-3" if current_user.id == @trip.user_id%>
    <%= link_to 'Delete', @trips, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger mr-3" if current_user.id == @trip.user_id %>
  </div>
</div>